### ISSUE TITLE
Remove Nick !

### ISSUE THREAD

**Issue by NickBurnett** [matthewsvu/HackUTD-Bot-Project#3]
### **_Remove Nathan._**

**Comment by matthewsvu** [comment]
Yes

**Comment by NickBurnett** [comment]
Sorry for the necro, but it appears that Nathan is still listed as a contributor for this project.

**Comment by danielkangel** [comment]
![image](https://user-images.githubusercontent.com/70451728/112741080-e3122800-8f47-11eb-9dee-9a76627360ae.png)

**Comment by NathanP9000** [comment]
Remove Nick !

**Comment by NickBurnett** [comment]
@danielkangel I appreciate your attempted assistance in this matter, but unfortunately, a simple screenshot will not help. Closure of an issue does not necessarily imply its resolve. While the issue is closed, there is no denying that this bug is persistent.

**Comment by danielkangel** [comment]
resolved
